In [189]:
import pandas as pd
import matplotlib.pyplot as plt
import sidetable as stb
import numpy as np
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from num2words import num2words
import nltk
from sklearn.decomposition import NMF

In [190]:
df1 = pd.read_csv('../data/books_25_pages_author_info_description.csv',skipinitialspace=True)
df1 = df1.rename(columns = lambda x: x.strip())
df1.head()

,book_reference,author_names,avg_rating,num_ratings,year_published,book_title,book_isbn,book_review_count,kindle_price,author_link,...,genre_urban-planning,genre_vegan,genre_war,genre_womens,genre_womens-studies,genre_world-war-ii,genre_writing,genre_young-adult,genre_zen,author_num_unique_books
0,/book/show/28257707-the-subtle-art-of-not-givi...,Mark Manson,3.94,515636,2016.0,The Subtle Art of Not Giving a F*ck,NaN,33082.0,NaN,https://www.goodreads.com/author/show/8529755....,...,0,0,0,0,0,0,0,0,0,36.0
1,/book/show/4865.How_to_Win_Friends_and_Influen...,Dale Carnegie,4.20,600309,1936.0,How to Win Friends and Influence People,NaN,15121.0,NaN,https://www.goodreads.com/author/show/3317.Dal...,...,0,0,0,0,0,0,0,0,0,396.0
2,/book/show/36072.The_7_Habits_of_Highly_Effect...,Stephen R. Covey,4.12,517025,1989.0,The 7 Habits of Highly Effective People,9.780743e+12,10277.0,NaN,https://www.goodreads.com/author/show/1538.Ste...,...,0,0,0,0,0,0,0,0,0,505.0
3,/book/show/12609433-the-power-of-habit,Charles Duhigg,4.10,337512,2012.0,The Power of Habit,9.781400e+12,16950.0,NaN,https://www.goodreads.com/author/show/5201530....,...,0,0,0,0,0,0,0,0,0,7.0
4,/book/show/22318578-the-life-changing-magic-of...,Marie Kond\xc5\x8d,3.84,275462,2011.0,The Life-Changing Magic of Tidying Up,9.781608e+12,27998.0,9.99,https://www.goodreads.com/author/show/5589647....,...,0,0,0,0,0,0,0,0,0,18.0

In [191]:
df2 = df1.copy() #[['book_title','book_description']]
df2.loc[:,['book_title','book_description']].stb.missing()

                  missing  total   percent
book_description       35   1249  2.802242
book_title              6   1249  0.480384

In [192]:
df3 = df2.dropna(subset=['book_description'])
df3.loc[:,['book_title','book_description']].stb.missing()

                  missing  total  percent
book_title              0   1214      0.0
book_description        0   1214      0.0

In [193]:
df4 = df3.copy()
df4['title_description'] = df3.apply(lambda x : x['book_title']+" "+x['book_description'],axis=1)
df4.head()

,book_reference,author_names,avg_rating,num_ratings,year_published,book_title,book_isbn,book_review_count,kindle_price,author_link,...,genre_vegan,genre_war,genre_womens,genre_womens-studies,genre_world-war-ii,genre_writing,genre_young-adult,genre_zen,author_num_unique_books,title_description
0,/book/show/28257707-the-subtle-art-of-not-givi...,Mark Manson,3.94,515636,2016.0,The Subtle Art of Not Giving a F*ck,NaN,33082.0,NaN,https://www.goodreads.com/author/show/8529755....,...,0,0,0,0,0,0,0,0,36.0,The Subtle Art of Not Giving a F*ck Alternate ...
1,/book/show/4865.How_to_Win_Friends_and_Influen...,Dale Carnegie,4.20,600309,1936.0,How to Win Friends and Influence People,NaN,15121.0,NaN,https://www.goodreads.com/author/show/3317.Dal...,...,0,0,0,0,0,0,0,0,396.0,How to Win Friends and Influence People ISBN 9...
2,/book/show/36072.The_7_Habits_of_Highly_Effect...,Stephen R. Covey,4.12,517025,1989.0,The 7 Habits of Highly Effective People,9.780743e+12,10277.0,NaN,https://www.goodreads.com/author/show/1538.Ste...,...,0,0,0,0,0,0,0,0,505.0,The 7 Habits of Highly Effective People When S...
3,/book/show/12609433-the-power-of-habit,Charles Duhigg,4.10,337512,2012.0,The Power of Habit,9.781400e+12,16950.0,NaN,https://www.goodreads.com/author/show/5201530....,...,0,0,0,0,0,0,0,0,7.0,The Power of Habit A young woman walks into a ...
4,/book/show/22318578-the-life-changing-magic-of...,Marie Kond\xc5\x8d,3.84,275462,2011.0,The Life-Changing Magic of Tidying Up,9.781608e+12,27998.0,9.99,https://www.goodreads.com/author/show/5589647....,...,0,0,0,0,0,0,0,0,18.0,The Life-Changing Magic of Tidying Up Despite ...

In [194]:
nltk.download('punkt')
def convert_lower_case(data):
    return np.char.lower(data)
def remove_stop_words(data):
    stop_words = stopwords.words('english')
    words = word_tokenize(str(data))
    new_text = ""
    for w in words:
        if w not in stop_words and len(w) > 1:
            new_text = new_text + " " + w
    return new_text
def remove_punctuation(data):
    symbols = "!\"#$%&()*+-./:;<=>?@[\]^_`{|}~\n"
    for i in range(len(symbols)):
        data = np.char.replace(data, symbols[i], ' ')
        data = np.char.replace(data, "  ", " ")
    data = np.char.replace(data, ',', '')
    return data
def remove_apostrophe(data):
    return np.char.replace(data, "'", "")
def stemming(data):
    stemmer= PorterStemmer()
    
    tokens = word_tokenize(str(data))
    new_text = ""
    for w in tokens:
        new_text = new_text + " " + stemmer.stem(w)
    return new_text
def convert_numbers(data):
    tokens = word_tokenize(str(data))
    new_text = ""
    for w in tokens:
        try:
            w = num2words(int(w))
        except:
            a = 0
        new_text = new_text + " " + w
    new_text = np.char.replace(new_text, "-", " ")
    return new_text
def remove_obvious(data):
    return_data = str(data).replace("book","").replace("self","").replace("help","").replace("author","").replace("peopl","person").replace("bestsel","").replace("reader","")
    return return_data 

def preprocess(data):
    data = convert_lower_case(data)
    data = remove_punctuation(data) #remove comma seperately
    data = remove_apostrophe(data)
    data = remove_stop_words(data)
    data = convert_numbers(data)
    data = stemming(data)
    data = remove_punctuation(data)
    data = convert_numbers(data)
    data = stemming(data) #needed again as we need to stem the words
    data = remove_punctuation(data) #needed again as num2word is giving few hypens and commas fourty-one
    data = remove_stop_words(data) #needed again as num2word is giving stop words 101 - one hundred and one
    data = remove_obvious(data)
    return data

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\valer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [195]:
clean_descriptions = []
current_descriptions = df4['title_description'].values
for i in range(0,len(current_descriptions)):
    clean_descriptions.append(preprocess(current_descriptions[i]))
df5 = df4.copy()
df5['title_description'] = clean_descriptions

In [196]:
vectorizer = TfidfVectorizer(max_df=0.8, 
#                                    min_df=1,
                                   max_features=30,
                                   stop_words='english')

In [197]:
X = vectorizer.fit_transform(df5['title_description'].values)
print(X.shape)
feature_names = vectorizer.get_feature_names()
dense_list = X.todense().tolist()
pd.DataFrame(dense_list, columns=feature_names).head(n=10)

(1214, 30)

,chang,day,everi,feel,guid,happi,learn,life,like,live,...,success,thing,think,time,use,want,way,work,world,year
0,0.000000,0.000000,0.000000,0.210077,0.210387,0.233872,0.180843,0.258455,0.206445,0.453875,...,0.000000,0.222380,0.216170,0.322135,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.135091,0.000000,0.000000,0.000000,0.000000,0.000000,0.134437,0.000000,0.153470,0.112469,...,0.155257,0.000000,0.160699,0.000000,0.000000,0.158275,0.492674,0.122898,0.000000,0.000000
2,0.092182,0.000000,0.108003,0.000000,0.000000,0.000000,0.000000,0.458875,0.000000,0.230238,...,0.317830,0.225615,0.000000,0.000000,0.203919,0.000000,0.084047,0.000000,0.000000,0.000000
3,0.308377,0.000000,0.240867,0.000000,0.000000,0.000000,0.102295,0.219296,0.000000,0.171159,...,0.472548,0.000000,0.000000,0.091109,0.000000,0.000000,0.093721,0.280544,0.000000,0.353895
4,0.365774,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.260113,0.831075,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.488962,0.000000,0.000000,0.000000,0.141523,0.000000,0.121649,0.086929,0.000000,0.101771,...,0.140488,0.000000,0.000000,0.216694,0.135206,0.429658,0.000000,0.000000,0.115922,0.000000
6,0.432071,0.173742,0.168741,0.000000,0.166743,0.000000,0.143327,0.307259,0.000000,0.000000,...,0.331047,0.000000,0.171326,0.127654,0.159300,0.168741,0.262627,0.131025,0.136579,0.000000
7,0.266168,0.000000,0.000000,0.000000,0.308154,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.305901,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.484288,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.443367,0.000000,0.000000,0.000000,0.286814,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,0.155359,0.000000,0.000000,0.000000,0.000000,0.399889,0.000000,0.110481,0.176496,0.517376,...,0.000000,0.000000,0.000000,0.137702,0.171838,0.000000,0.141649,0.000000,0.294657,0.000000

In [198]:
n_topics = 20
n_top_words = 15
nmf = NMF(n_components=n_topics, random_state=1).fit(X)

feature_names = vectorizer.get_feature_names()

In [199]:
def print_top_words(model, feature_names, n_top_words):
    topic_dict = {}
    for topic_idx, topic in enumerate(model.components_):
        topic_dict[topic_idx] = []
        feature_names_topic = [feature_names[i] for i in topic.argsort()[:-n_top_words - 1:-1]]
        feature_weights_topic = [topic[i] for i in topic.argsort()[:-n_top_words - 1:-1]]
        feature_weights_topic = [str(round(weight_topic,2)) for weight_topic in feature_weights_topic]
        print(topic_idx,end=', ')
        for i in range(0,len(feature_weights_topic)):
            print(feature_weights_topic[i]+"*"+feature_names_topic[i],end=", ")
        print()

    
# pd.DataFrame(nmf.components_)
print_top_words(nmf, feature_names, n_top_words)

0, 4.24*new, 0.47*guid, 0.39*offer, 0.23*practic, 0.02*need, 0.0*day, 0.0*everi, 0.0*feel, 0.0*happi, 0.0*learn, 0.0*life, 0.0*like, 0.0*live, 0.0*love, 0.0*make,
1, 2.57*life, 0.17*guid, 0.1*want, 0.05*use, 0.02*need, 0.0*chang, 0.0*day, 0.0*everi, 0.0*feel, 0.0*happi, 0.0*learn, 0.0*like, 0.0*live, 0.0*love, 0.0*make,
2, 2.47*love, 0.67*relationship, 0.31*feel, 0.22*need, 0.2*want, 0.17*guid, 0.15*offer, 0.13*practic, 0.04*like, 0.0*chang, 0.0*life, 0.0*make, 0.0*happi, 0.0*live, 0.0*everi,
3, 2.37*person, 0.17*relationship, 0.17*offer, 0.15*use, 0.13*guid, 0.1*like, 0.04*need, 0.02*practic, 0.0*year, 0.0*live, 0.0*life, 0.0*make, 0.0*learn, 0.0*happi, 0.0*feel,
4, 2.45*mind, 0.46*practic, 0.3*offer, 0.11*use, 0.04*guid, 0.0*year, 0.0*day, 0.0*everi, 0.0*feel, 0.0*happi, 0.0*learn, 0.0*life, 0.0*like, 0.0*live, 0.0*love,
5, 2.62*make, 0.41*use, 0.15*like, 0.03*want, 0.02*relationship, 0.0*chang, 0.0*mind, 0.0*day, 0.0*everi, 0.0*feel, 0.0*guid, 0.0*happi, 0.0*learn, 0.0*life, 0.0*live,
6, 3.0*happi, 0.29*feel, 0.09*practic, 0.02*offer, 0.01*relationship, 0.0*guid, 0.0*want, 0.0*year, 0.0*love, 0.0*live, 0.0*like, 0.0*learn, 0.0*life, 0.0*mind, 0.0*everi,
7, 2.55*work, 0.23*practic, 0.21*need, 0.16*guid, 0.13*offer, 0.05*relationship, 0.04*use, 0.0*year, 0.0*live, 0.0*like, 0.0*life, 0.0*learn, 0.0*make, 0.0*happi, 0.0*feel,
8, 2.73*success, 0.33*want, 0.3*guid, 0.15*practic, 0.04*everi, 0.02*like, 0.01*need, 0.0*make, 0.0*love, 0.0*live, 0.0*year, 0.0*life, 0.0*mind, 0.0*happi, 0.0*feel,
9, 2.64*think, 0.28*like, 0.28*need, 0.2*want, 0.07*relationship, 0.04*use, 0.0*love, 0.0*live, 0.0*life, 0.0*learn, 0.0*year, 0.0*happi, 0.0*make, 0.0*feel, 0.0*everi,
10, 2.69*power, 0.27*use, 0.18*relationship, 0.15*guid, 0.03*practic, 0.02*everi, 0.02*offer, 0.02*want, 0.0*year, 0.0*live, 0.0*like, 0.0*life, 0.0*learn, 0.0*make, 0.0*happi,
11, 2.89*chang, 0.0*world, 0.0*day, 0.0*everi, 0.0*feel, 0.0*guid, 0.0*happi, 0.0*learn, 0.0*life, 0.0*like, 0.0*live, 0.0*love, 0.0*make, 0.0*mind, 0.0*need,
12, 2.95*time, 0.19*like, 0.15*practic, 0.03*use, 0.0*year, 0.0*mind, 0.0*day, 0.0*everi, 0.0*feel, 0.0*guid, 0.0*happi, 0.0*learn, 0.0*life, 0.0*live, 0.0*love,
13, 1.85*day, 1.45*everi, 1.06*feel, 0.29*use, 0.28*like, 0.06*want, 0.06*need, 0.03*offer, 0.03*relationship, 0.02*practic, 0.0*chang, 0.0*live, 0.0*learn, 0.0*life, 0.0*make,
14, 2.46*thing, 0.5*like, 0.25*offer, 0.16*practic, 0.08*want, 0.07*need, 0.07*feel, 0.0*guid, 0.0*happi, 0.0*make, 0.0*learn, 0.0*life, 0.0*everi, 0.0*live, 0.0*day,
15, 2.55*learn, 0.21*feel, 0.18*want, 0.11*use, 0.09*need, 0.09*practic, 0.07*like, 0.04*guid, 0.0*make, 0.0*love, 0.0*live, 0.0*year, 0.0*life, 0.0*mind, 0.0*everi,
16, 2.99*world, 0.34*need, 0.15*everi, 0.03*like, 0.01*offer, 0.0*chang, 0.0*day, 0.0*feel, 0.0*guid, 0.0*happi, 0.0*learn, 0.0*life, 0.0*live, 0.0*love, 0.0*make,
17, 2.65*way, 0.31*want, 0.03*like, 0.03*relationship, 0.02*offer, 0.0*chang, 0.0*love, 0.0*live, 0.0*life, 0.0*happi, 0.0*learn, 0.0*mind, 0.0*guid, 0.0*feel, 0.0*everi,
18, 2.89*year, 0.42*relationship, 0.28*use, 0.07*practic, 0.01*like, 0.01*everi, 0.0*chang, 0.0*think, 0.0*love, 0.0*day, 0.0*work, 0.0*feel, 0.0*guid, 0.0*happi, 0.0*learn,
19, 2.91*live, 0.27*practic, 0.22*need, 0.14*offer, 0.12*want, 0.1*like, 0.08*feel, 0.0*make, 0.0*love, 0.0*year, 0.0*life, 0.0*mind, 0.0*happi, 0.0*guid, 0.0*everi,

0: people

1: life

2: love

3: new
4: mind
5: make
6: live
7: success
8: way
9: think
10: happy
11: work
12: power
13: world
14: change
15: guide
15: year
17: learn
18: feel

In [210]:
# descr_temp = "When Stephen Covey first released The Seven Habits of Highly Effective People, the book became an instant rage because people suddenly got up and took notice that their lives were headed off in the wrong direction; and more than that, they realized that there were so many simple things they could do in order to navigate their life correctly. This book was wonderful education for people, education in how to live life effectively and get closer to the ideal of being a â€˜successâ€™ in life.But not everyone understands Stephen Coveyâ€™s model fully well, or maybe there are some people who havenâ€™t read it yet. This is definitely true because we still see so much failure all around us. Now, I am not saying that by using Coveyâ€™s model, or anyone elseâ€™s model for that matter, you can become a sure-shot success, but at least we should have seen many more successes around us already judging by the number of copies the book has sold! So, where is the shortcoming?There are two main problems here, and we are talking only about the people who have read the book already. The first problem is that most people are too lazy to implement the ideals of Stephen Covey in their lives. They consider his masterpiece of a book as a mere coffee-table book or a book that you use for light reading when you are traveling and then forget all about it. They do not realize that this book contains life-changing information. Or, they take the information and do not make the effort to actually utilize it so that it becomes knowledge for them.The second problem is that a lot of people have a myopic view of Coveyâ€™s ideals. These are people who are impressed by the book already. If you ask them what the seven habits are, they can rattle them off end to end, but then they miss the larger picture. They do not understand that Covey was trying to tell more than he wrote in words. There are hidden implications in this book, yes, and a lot of people have just failed to see through them.That is what we are trying to do. We are trying to show you how Coveyâ€™s book, or rather, his model, was a complete model in itself. There was nothing amiss about it. If you implement it, there should be no aspect of your life that should go untouched. The only thing is that you have to understand these ideals and try to implement them in your life. But, before we barge into that area, it is extremely important to understand what these ideals are. What was the model that was propounded by Stephen Covey in his mega-famous book? We shall begin by trying to understand his model first, and then interpret it in such a way that it pertains to every aspect of our life"
# temp_2 = vectorizer.transform([preprocess(descr_temp)]).todense().tolist()

# for i in range(0,len(nmf.transform(temp_2)[0])):
#     print(i,nmf.transform(temp_2)[0][i])

transform_x = nmf.transform(X)
for nmfi in transform_x:
    for i in range(0,n_topics):
        nmfi[i] = 1 if nmfi[i] > 0.1 else 0

df6 = pd.DataFrame(transform_x,columns = range(0,n_topics))
df7 = df6.copy()
df7['sum'] = df6[df6.columns[0::]].sum(axis=1)
df7.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,sum
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0
2,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [211]:
print(len(df7[df7['sum']==0].index))
df8 = df7.drop('sum', axis=1)
df8.head()

38

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [212]:
df5.join(df8).head()

,book_reference,author_names,avg_rating,num_ratings,year_published,book_title,book_isbn,book_review_count,kindle_price,author_link,...,10,11,12,13,14,15,16,17,18,19
0,/book/show/28257707-the-subtle-art-of-not-givi...,Mark Manson,3.94,515636,2016.0,The Subtle Art of Not Giving a F*ck,NaN,33082.0,NaN,https://www.goodreads.com/author/show/8529755....,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,/book/show/4865.How_to_Win_Friends_and_Influen...,Dale Carnegie,4.20,600309,1936.0,How to Win Friends and Influence People,NaN,15121.0,NaN,https://www.goodreads.com/author/show/3317.Dal...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,/book/show/36072.The_7_Habits_of_Highly_Effect...,Stephen R. Covey,4.12,517025,1989.0,The 7 Habits of Highly Effective People,9.780743e+12,10277.0,NaN,https://www.goodreads.com/author/show/1538.Ste...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/book/show/12609433-the-power-of-habit,Charles Duhigg,4.10,337512,2012.0,The Power of Habit,9.781400e+12,16950.0,NaN,https://www.goodreads.com/author/show/5201530....,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,/book/show/22318578-the-life-changing-magic-of...,Marie Kond\xc5\x8d,3.84,275462,2011.0,The Life-Changing Magic of Tidying Up,9.781608e+12,27998.0,9.99,https://www.goodreads.com/author/show/5589647....,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [213]:
df5.join(df8).to_csv('../data/books_25_pages_author_info_description_nmf.csv',index=False)